general.import = ["~/.config/alacritty/themes/gruber_darker.toml"]


[font]
size = 12.0

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[keyboard]
bindings = [
{ key = "m", mods = "Control|Shift", action = "SpawnNewInstance" },
]

# [window]
# opacity = 0.95

[window.padding]
x = 0
y = 0

