general.import = ["~/.config/alacritty/themes/gruber_darker.toml"]

# [env]
# TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[keyboard]
bindings = [{ key = "m", mods = "Control|Shift", action = "SpawnNewInstance" }]

# [window]
# opacity = 0.95

[window.padding]
x = 0
y = 0
